version: '3.8'

services:
  print-scan:
    image: ghcr.io/alexjbarnes/homelab/print-scan:latest
    container_name: print-scan
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./cups-spool:/var/spool/cups
    environment:
      - TZ=Europe/London
