version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      test: ${LATEST_COMPOSE_DIR:-$(ls -d /var/lib/docker/volumes/portainer_data/_data/compose/* | sort -n | tail -1)}
volumes:
  caddy_data:
  caddy_config:
    
