version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: Kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        dns:
            - 1.1.1.1
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=${USERNAME}
            - --server-password=${PASSWORD}
        environment:
            # Set repository password
            KOPIA_PASSWORD: ${PASSWORD}
            USER: ${USERNAME}
        volumes:
            # Mount local folders needed by kopia
            - kopia_config:/app/config
            - kopia_cache:/app/cache
            - kopia_logs:/app/logs
            # Mount local folders to snapshot
            - /var/lib/docker/volumes:/data:ro
            # Mount repository location
            - /mnt/sda1_backup:/repository/sda1
            - /mnt/sdb1_backup:/repository/sdb1
            # Mount path for browsing mounted snapshots
            # - /tmp:/tmp:shared

    
volumes:
    kopia_config:
    kopia_cache:
    kopia_logs:
        
