version: "3"

services:
  debrid-downloader:
    image: ghcr.io/alexjbarnes/debrid-downloader:main
    ports:
      - 3333:3000
    volumes:
      - /debrid-downloader/database:/database
      - type: bind
        source: /mnt/media
        target: /media
    environment:
      DATABASE_PATH: /database/debrid.db
      BASE_DOWNLOADS_PATH: /media/
      ALLDEBRID_API_KEY: ${ALLDEBRID_API_KEY}
