version: "3"

services:
  debrid-downloader:
    image: ghcr.io/alexjbarnes/debrid-downloader:main
    user: "1000:2000"
    ports:
      - 3333:3000
    volumes:
      - debrid_db:/database
      - type: bind
        source: /mnt/media
        target: /media
    environment:
      DATABASE_PATH: /database/debrid.db
      BASE_DOWNLOADS_PATH: /media/
      ALLDEBRID_API_KEY: ${ALLDEBRID_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}

volumes:
  debrid_db:
