services:
  voicebox:
    build:
      context: https://github.com/jamiepine/voicebox.git
    container_name: voicebox
    restart: unless-stopped

    ports:
      - "17493:17493"

    volumes:
      - type: bind
        source: ./output
        target: /app/data/generations
      - voicebox-data:/app/data

    environment:
      - LOG_LEVEL=info
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - HF_HOME=/app/data/huggingface

    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

volumes:
  voicebox-data:
