services:
  git-clone:
    image: alpine/git
    volumes:
      - type: bind
        source: /config-repo
        target: /repo
        read_only: false
    command: git pull https://github.com/alexjbarnes/HomeLab.git /repo
    restart: "no"  # Run once and stop
