services:
  git-clone:
    image: alpine/git
    volumes:
      - config-repo:/repo
    command: clone https://github.com/alexjbarnes/HomeLab.git /repo
    restart: "no"  # Run once and stop

volumes:
  config-repo:
