services:
  git-clone:
    image: cgr.dev/chainguard/wolfi-base
    volumes:
      - type: bind
        source: /config-repo
        target: /repo
        read_only: false
    command: apk add git && find /repo -mindepth 1 -exec rm -rf {} + && git clone https://github.com/alexjbarnes/HomeLab.git /repo
    restart: "no"  # Run once and stop
