version: "3.8"
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - backrest_data:/data
      - backrest_config:/config
      - backrest_cache:/cache
      - backrest_tmp:/tmp
      #- ./backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - /var/lib/docker/volumes:/docker_volumes  # Mount local paths to backup
      - /mnt/immich:/mnt/immich
      - /mnt/backup_sda1:/repos/sda1
      - /mnt/backup_sdb1:/repos/sdb1
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    ports:
      - "9898:9898"
    restart: unless-stopped
volumes:
    backrest_data:
    backrest_config:
    backrest_cache:
    backrest_tmp:
